#!/bin/bash

# Stop on errors, print commands
set -e
set -x

# Set up environment for Flask debug server
export FLASK_DEBUG=True
export FLASK_APP=summarize

# Run development server
flask run --host 0.0.0.0 --port 8000
